---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# python-dynamic-version-action
name: "ðŸ Check Python Project for Dynamic Versioning"
description: "Checks if dynamic versioning is enabled in pyproject.toml"

inputs:
  # Optional
  PATH_PREFIX:
    description: "Directory location containing project code"
    type: string
    required: false
    default: ""
outputs:
  DYNAMIC_VERSION:
    description: "Set true when dynamic versioning configured"
    value: ${{ steps.parse.outputs.dynamic_version }}

runs:
  using: "composite"
  steps:
    - name: "Check for required pyproject.toml file"
      # yamllint disable-line rule:line-length
      uses: lfreleng-actions/path-check-action@554ef2267e6810ab7ac56506c8c1fd00725d59b1 # v0.1.0
      with:
        path: "${{ inputs.path_prefix }}pyproject.toml"

    - id: parse
      name: "Check for dynamic project versioning"
      shell: bash
      run: |
        # Check for dynamic project versioning
        if (grep -q 'dynamic = \["version"\]' \
          ${{ inputs.path_prefix }}pyproject.toml); then
          echo "Dynamic versioning configured âœ…"
          echo "dynamic_version=true" >> "$GITHUB_ENV"
          echo "dynamic_version=true" >> "$GITHUB_OUTPUT"
        else
          echo "Dynamic versioning NOT configured"
          echo "dynamic_version=false" >> "$GITHUB_ENV"
          echo "dynamic_version=false" >> "$GITHUB_OUTPUT"
        fi
